-- SCRIPT SQL ORACLE
-- CREATION DU SCHEMA DE LA BASE ET INSERTION D'UN JEU DE DONNEE

-- CREATION
CREATE TABLE UTILISATEURS
(
    identifiant VARCHAR2(30) NOT NULL,
    motdepasse  VARCHAR2(50) NOT NULL,
    PRIMARY KEY (identifiant)
);

CREATE TABLE DOCUMENTS
(
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    type NUMBER NOT NULL,
    titre VARCHAR(50) NOT NULL,
    auteur VARCHAR(50) NOT NULL,
    emprunt NUMBER(1,0),
    idAbonne NUMBER,
    PRIMARY KEY (id),
    CONSTRAINT fk_idAbonne FOREIGN KEY (idAbonne) REFERENCES ABONNES(id)
);

CREATE TABLE ABONNES
(
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nom VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    age NUMBER NOT NULL,
    dateNaissance DATE NOT NULL,
    suspendu NUMBER(1,0)
);

-- INSERTION DONNEES
INSERT INTO UTILISATEURS (identifiant, motdepasse)
VALUES ('admin','admin');
INSERT INTO UTILISATEURS (identifiant, motdepasse)
VALUES ('user','user');

INSERT INTO DOCUMENTS (type, titre, auteur, emprunt)
VALUES (2,'Stars Wars, épisode I : La Menace fantome','Georges Lucas', 1);
INSERT INTO DOCUMENTS (type, titre, auteur, emprunt)
VALUES (2,'Full Metal Jacket','Stanley Kubric', 1);
INSERT INTO DOCUMENTS (type, titre, auteur, emprunt)
VALUES (2,'Les Dents de la mer','Steven Spielberg', 0);
INSERT INTO DOCUMENTS (type, titre, auteur, emprunt)
VALUES (2,'Gravity','Alfonso Cuaron', 1);
INSERT INTO DOCUMENTS (type, titre, auteur, emprunt)
VALUES (2,'Big Fish','Tim Burton', 0);
INSERT INTO DOCUMENTS (type, titre, auteur, emprunt)
VALUES (1,'Le crepuscule des fauves','Marc Levy', 0);
INSERT INTO DOCUMENTS (type, titre, auteur, emprunt)
VALUES (1,'Si ça saigne','Stephen King', 1);
INSERT INTO DOCUMENTS (type, titre, auteur, emprunt)
VALUES (1,'L''art subtil de s''en foutre','Mark Manson', 1);
INSERT INTO DOCUMENTS (type, titre, auteur, emprunt)
VALUES (1,'L''enigme de la chambre 622','Joel Dicker', 0);
INSERT INTO DOCUMENTS (type, titre, auteur, emprunt)
VALUES (1,'Une terre promise','Barack Obama', 1);
INSERT INTO DOCUMENTS (type, titre, auteur, emprunt)
VALUES (3,'Random access memories','Daft Punk', 1);
INSERT INTO DOCUMENTS (type, titre, auteur, emprunt)
VALUES (3,'After Hours','The Weeknd', 0);
INSERT INTO DOCUMENTS (type, titre, auteur, emprunt)
VALUES (3,'Chopin','Khatia Buniatishvili', 1);
INSERT INTO DOCUMENTS (type, titre, auteur, emprunt)
VALUES (3,'Sunset In The Blue','Melody Gradot', 1);
INSERT INTO DOCUMENTS (type, titre, auteur, emprunt)
VALUES (3,'Feu','Nekfeu', 0);

COMMIT;