-- Create
CREATE TABLE UTILISATEURS
(
    identifiant VARCHAR2(30) NOT NULL,
    motdepasse  VARCHAR2(50) NOT NULL,
    PRIMARY KEY (identifiant)
);

CREATE TABLE DOCUMENTS
(
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    type NUMBER NOT NULL,
    titre VARCHAR(50) NOT NULL,
    auteur VARCHAR(50) NOT NULL,
    emprunt NUMBER(1,0),
    PRIMARY KEY (id)
);

-- Insert
INSERT INTO UTILISATEURS (identifiant, motdepasse)
VALUES ('admin','admin');
INSERT INTO UTILISATEURS (identifiant, motdepasse)
VALUES ('user','user');

INSERT INTO DOCUMENTS (type, titre, AUTEUR)
VALUES (1,'Stars Wars','BLOB');
INSERT INTO DOCUMENTS (type, titre, AUTEUR)
VALUES (2,'...','BLOB');
INSERT INTO DOCUMENTS (type, titre, AUTEUR)
VALUES (3,'....','BLOB');

COMMIT;